# create ATP database & compute node to run a swingbench test
#
# first, the database...
- name : get the .tf files from git, & make a matching database called "{{ p_db_name }}"
  hosts: localhost
  
  vars:
    v_git_repo_url:      "{{ p_git_repo }}"
    v_git_clone_dest:    "{{ p_clone_dest }}"
    v_db_name:           "{{ p_db_name }}"
    
  tasks:
    # get .tf files from git repo
    - include_tasks: git/clone-repo.yaml
      vars:
        v_git_repo:      "{{ v_git_repo_url }}"
        v_clone_dest:    "{{ v_git_clone_dest }}"

    # put the required database name into the variables.tf file
    #- lineinfile:
    #    path:            "{{ v_git_clone_dest }}/docs/examples/database/atp/variables.tf"
    #    regexp:          '^  default = "atpdb1"' 
    #    line:            '  default = "{{ v_db_name }}"'
    #    state:           present

    # make sure the db admin password has at least one numeric character (or the database creation fails)
    - lineinfile:
        path:            "{{ v_git_clone_dest }}/docs/examples/database/atp/autonomous_database.tf"
        insertafter:     '^resource "random_string" "autonomous_database_admin_password" {'
        line:            '  min_numeric = 1'
        state:           present

    # create database based on .tf files
    - include_tasks: database/create-atp.yaml
      vars:
        v_tf_location:   "{{ v_git_clone_dest }}/docs/examples/database/atp/"
        v_database_name: "{{ v_db_name }}"

    # create networking
    # create compute node
    # configure compute node
    # run swingbench OE benchmark setup
    # run a test
