# create ATP database & compute node to run a swingbench test
- name : create ATP database
  hosts: localhost
  tasks:
    # create database
    - include_tasks: database/create-atp.yaml

    # create networking
    # create compute node
    # configure compute node
    # run swingbench OE benchmark setup
    # run a test
